/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */  
package coq;

import org.openide.util.NbPreferences;

final class CoqOptionsPanel extends javax.swing.JPanel {

    private final CoqOptionsOptionsPanelController controller;

    CoqOptionsPanel(CoqOptionsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    initParams = new javax.swing.JComboBox();

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CoqOptionsPanel.class, "CoqOptionsPanel.jLabel1.text")); // NOI18N

    jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    jTextField1.setText(org.openide.util.NbBundle.getMessage(CoqOptionsPanel.class, "CoqOptionsPanel.jTextField1.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CoqOptionsPanel.class, "CoqOptionsPanel.jLabel2.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(CoqOptionsPanel.class, "CoqOptionsPanel.jLabel3.text")); // NOI18N

    initParams.setEditable(true);
    initParams.setToolTipText(org.openide.util.NbBundle.getMessage(CoqOptionsPanel.class, "CoqOptionsPanel.initParams.toolTipText")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(49, 49, 49)
            .addComponent(jLabel2))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(initParams, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(initParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
        .addComponent(jLabel2))
    );
  }// </editor-fold>//GEN-END:initComponents
    public static final String COQPATH_KEY="CoqPath";
    public static final String COQOPTIONS_KEY="CoqOptions";
    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(CoqOptionsPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(CoqOptionsPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        String coqtop=NbPreferences.forModule(CoqOptionsPanel.class).get(COQPATH_KEY, "");
        String coqOptionLines=NbPreferences.forModule(CoqOptionsPanel.class).get(COQOPTIONS_KEY, "");
        if(coqtop==null || coqtop.isEmpty())
        {
            coqtop="coqtop";
        }
        if(coqOptionLines==null)
        {
            coqOptionLines="";
        }
        jTextField1.setText(coqtop);
        String [] coqOpLines = coqOptionLines.split("\n");
        // one could remove duplicates here
        for(String optionLine : coqOpLines)
          if(!optionLine.isEmpty())
            initParams.addItem(optionLine);
        initParams.setSelectedIndex(0);
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(CoqOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(CoqOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        NbPreferences.forModule(CoqOptionsPanel.class).put(COQPATH_KEY, jTextField1.getText());
        String appended="";
        int selectedIndex = initParams.getSelectedIndex();
        //put the selected item first because the coqtop initializer picks this one
        appended = appended + initParams.getSelectedItem() + "\n";
        for(int i =0; i<initParams.getItemCount();i++)
        {
            if(i!=selectedIndex)
            appended = appended + ((String) initParams.getItemAt(i) + "\n");
        }
        
        NbPreferences.forModule(CoqOptionsPanel.class).put(COQOPTIONS_KEY, appended);
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox initParams;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables
}
